# -*- coding: utf-8 -*-
"""Test__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qti-XuIkSVG_zkdPJcPg8bIu0cE38XJW

Installing the neccesary  *libraries*
"""

pip install transformers torch datasets

from transformers import DistilBertTokenizer, DistilBertForSequenceClassification

model_name = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = DistilBertTokenizer.from_pretrained(model_name)
model = DistilBertForSequenceClassification.from_pretrained(model_name)

def preprocess_text(text):
    return tokenizer.encode(text, return_tensors="pt", max_length=512, truncation=True)

def analyze_sentiment(text):
    inputs = preprocess_text(text)
    outputs = model(inputs)
    logits = outputs.logits
    predicted_class = logits.argmax().item()
    sentiment = "Positive" if predicted_class == 1 else "Negative"
    return sentiment

sample_text = "Climate change is a serious issue that needs immediate attention."
sentiment = analyze_sentiment(sample_text)
print(f"Sentiment: {sentiment}")

from transformers import Trainer, TrainingArguments
from datasets import load_dataset

ds = load_dataset("sentence-transformers/msmarco-msmarco-distilbert-base-tas-b", "triplet")

